### PR TITLE
Add move_index to change the position of an entry

### PR DESCRIPTION
**Pull request by cuviper**
This moves the position of a key-value pair from one index to another by
shifting all other pairs in-between, making this an O(n) operation.

This could be used as a building-block for other operations, like #173
which wants to insert at a particular index. You can `insert_full` to
insert it _somewhere_, then choose whether to `move_index` depending on
whether you want to also change pre-existing entries.

### CODE REVIEW

**Comment by cuviper** [comment]
I'm not entirely committed to the name `move_index`. It's somewhat similar to `swap_indices`, but I chose singular `index` because the movement of the one `from` index is the main point, while all the other shifted indices are a side-effect. Semantically, this is equivalent to `let value = vec.remove(from); vec.insert(to);`, or a slice rotation as this implementation actually does in its `entries`. Maybe `shift` or `rotate` would be better in the name.

**Comment by cuviper** [comment]
I just noticed that #83 had a similar method called `reorder_entry_index`.

**Comment by praveenperera** [comment]
I would love to get access to this function. Still thinking about merging it in?

**Comment by cuviper** [comment]
Sure -- do you have any thoughts about the name?

**Comment by praveenperera** [comment]
I think move_index works best. 

Reads really nicely as move index from x to y

**Comment by praveenperera** [comment]
I tried the function out on my [fork](https://github.com/praveenperera/indexmap). 

Visually it sometimes does not work in an intuitive way. For example if you move the the item to the second item in the set, it actually moves it to the end. Also if you're moving it an index over, it moves two spaces down. The function is still useful though. 

I just ended up doing: 

1. `shift_remove`
2. `insert`
3. `move` index

It's possible I was using it wrong, it's been a long day. I will confirm tomorrow with a test. But thought I'd mention it.

**Comment by praveenperera** [comment]
Ignore my last comment if you saw it (now deleted). This works great, I tired it out on my fork. This is exactly what I needed to make IndexSet and IndexMap work with my data structure.

**Pull request merged**
