### PR TITLE
Implement IntoDeserializer for IndexMap/IndexSet

### LINKED ISSUE #86: Implement serde::IntoDeserializer for IndexMap/IndexSet
It must be trivial because serde already has generic [`MapDeserializer`]: https://docs.serde.rs/src/serde/de/value.rs.html#1254-1266

[`MapDeserializer`]: https://docs.serde.rs/serde/de/value/struct.MapDeserializer.html

### PR DESCRIPTION
**Pull request by Mingun**
Fixes #86

### CODE REVIEW

**Comment by bluss** [comment]
Thanks. I'd generally prefer avoiding bumping versions in feature PRs, best leave the versions to the mantainers. That said, adding to the changelog is great, so we still risk merge conflicts there.

**Comment by bluss** [comment]
I see that we don't test serde on the minimum version in travis. Can we figure out the earliest possible version we can test serde on?

**Comment by cuviper** [comment]
I tried this PR with serde_test reverted back to 1.0.5, and used `cargo update -Zminimal-versions`. Everything was fine except we need fnv 1.0.5 for `FnvBuildHasher`.

**Comment by Mingun** [comment]
The reason for which I bump version of the `serde_test` in avoiding a lot of copies of the same libraries taking the place on the developer machine working with many projects. When all dependences use the latest versions, it is less probable. Besides, I do not see any reason not to bump the versions of the test dependencies, especially, if all changes are compatible. With high probability, there something is fixed. However, if you against such approach, I can revert this change

**Comment by cuviper** [comment]
Please do revert the bumped dependency, then we should merge this.

Remember that Cargo uses semver compatibility to resolve dependencies, so "avoiding a lot of copies" is not really an issue. Having `serde_test = "1.0.5"` is equivalent to `"^1.0.5"` or `">=1.0.5 <2.0.0"`. It would only pin an exact dependency with `serde_test = "=1.0.5"`.

**Comment by Mingun** [comment]
Done.

**Comment by cuviper** [comment]
Thanks!

**Pull request merged**
