### PR TITLE
Update to hashbrown 0.9

### PR DESCRIPTION
**Pull request by mbrubeck**
Note: This increases the MSRV to Rust 1.36.

### CODE REVIEW

**Comment by mbrubeck** [comment]
Note: If keeping the MSRV at 1.32 is a priority, hashbrown 0.9 could be changed to support that version, except when building with the optional `rayon` feature and the latest version of `crossbeam`.

**Comment by cuviper** [comment]
I'm OK with raising MSRV with a minor version bump. My support threshold for a crate like this is about a year, and 1.36 was released 2019-07-04.

I was looking for interesting new features, and `const fn new` would be nice, but we'll need `Vec::new` too (Rust 1.39).

If you're itching for a release, go ahead and bump to 1.6.0 and I'll publish.

**Comment by mbrubeck** [comment]
Bumped the minor version.

**Comment by cuviper** [comment]
Thanks!

**Pull request merged**
